### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Karla02** [alansary/HospitalCMS#1]
What is the username and password?

alansary - alansary  is not working

**Comment by alansary** [comment]
Username: alansary
Password: 123456

**Comment by gatas7** [comment]
i get these on using 
Username: alansary
Password: 123456
for login
SQLSTATE[HY000] [1045] Access denied for user 'alansary'@'localhost' (using password: YES)

**Comment by alansary** [comment]
Dear, you must use your database credentials, you could get these credentials by trying to login to phpmyadminlocalhost/phpmyadminBy default the credentials would be:Username: adminPassword:With empty password.

Sent from Yahoo Mail on Android 
 
  On Wed, 27 Mar 2019 at 7:39 pm, gatas7<notifications@github.com> wrote:   
i get these on using
Username: alansary
Password: 123456
for login
SQLSTATE[HY000] [1045] Access denied for user 'alansary'@'localhost' (using password: YES)
